### ISSUE TITLE
finaly

### ISSUE THREAD

**Issue by NotHuza** [abdullahbaa5/SCEditor#3]
After years of no new ultrapowa stile sc editors we got updated one good job do u have ds server are u dark souls guy i remember him long time ago d:

**Comment by abdofallah** [comment]
Hahaha yes its has been a long time since someone continued developing one so I decided to do it myself.

And yes ;) the og darksoulcoc.

**Comment by kareem7778d57** [comment]
Bro. How  I do install this tool

**Comment by abdofallah** [comment]
> Bro. How I do install this tool

build it with visual studio on a windows computer or download precompiled from release page

**Comment by Jrathuvithana** [comment]
@abdudsoul this software not working. Can u check?

**Comment by Voulqy** [comment]
> @abdudsoul this software not working. Can u check?

It's pretty hit or miss. It seems to work on an older version of Clash of Clans (pre-TH15). The more latest updates of the game don't seem to import into the game.

**Comment by abdofallah** [comment]
> > @abdudsoul this software not working. Can u check?
> 
> It's pretty hit or miss. It seems to work on an older version of Clash of Clans (pre-TH15). The more latest updates of the game don't seem to import into the game.

it works with all versions of the game (coc,cr,bb,bs).. you just have to find the exact steps to make it not crash (always run it via visual studio in debug mode)
