### ISSUE TITLE
Error when importing .sc files from newer versions of Clash of Clans.

### ISSUE THREAD

**Issue by Voulqy** [abdullahbaa5/SCEditor#4]
This seems to be happening on more newer versions of Clash of Clans. 

From what I can tell, v.13.675.2 of Clash of Clans works (from March 2021), but anything later doesn't. Maybe a new form of encryption is being used that this project doesn't support.

This is the error when trying to import buildings.sc & buildings_tex.sc:
![err](https://github.com/abdullahbaa5/SCEditor/assets/47714156/548ea0a2-597c-48d8-8eb4-fb28ab5ec4a9)

**Comment by lukastaia** [comment]
same error for brawl stars.

**Comment by Fluke458** [comment]
It appears that Clash Of Clans version higher than v.15.352.22 cannot be imported and have a new encoding format that is not supported by this project

This is the error when trying to import buildings.sc & buildings_tex.sc
![SC Editor 29_2_2567 11_04_17](https://github.com/abdullahbaa5/SCEditor/assets/141992636/2d574162-545f-4895-918d-f0e9def42c9d)

**Comment by abdofallah** [comment]
added support in latest commit 217503280df7e770d0590e3ee1d689afdec1878f
